### ISSUE TITLE
Disambiguate bindings of same name when printing terms

### ISSUE THREAD

**Issue by TurtlePU** [TurtlePU/lambda-calculus#1]
As we now, extra care must be taken while implementing substitution in lambda calculus. This implementation uses De Bruijn indices:
```haskell
\x. \y. (\f. \x. f y) (\y. x) y
~ \. \. (\. \. 1 2) (\. 2) 0
-> \. \. (\. (\. 3) 1) 0
-> \. \. (\. 2) 0
-> \. \. 1
```
However, we do not drop the original string names after name resolution &mdash; we might need to print the term later.

Printing right now is naive, e.g. the following is not elaborated at all (although name resolution and substitution work as expected):
```haskell
(\x. x (\x x. x x x) x x (x x)) (\x. x (\x. x) x)
```

I propose adding numeric labels for duplicate nested names (the similar solution is done in Haskell for inferred type variables):
```haskell
(\x0. x0 (\x1 x2. x2 x2 x2) x0 x0 (x0 x0)) (\x0. x0 (\x1. x1) x0)
```

One possible solution is annotating variables with corresponding De Bruijn *levels* once we detect that we need disambiguation.

**Comment by TurtlePU** [comment]
Decided to label as a bug because, without it, we sometimes cannot paste back the output of a REPL.

**Comment by Jijasan** [comment]
Reserse
